<?php
/**
*
* Copyright CKApps.com
* email: app@ckapps.com
*
*/
?>



<fieldset class="form-divst">
	<?php $_code=$this->getMethodCode() ?>
	<ul id="payment_form_<?php echo $_code ?>" style="display:none">
		<div style="height:30px;">
			<div style="width:120px;margin-left:10px;float:left;"><img width="300" height="150" border="0"  alt="支付宝" src="http://pic5.nipic.com/20100120/2438952_212447002403_2.jpg"/> </div>   
		</div>
		<div style="clear:both;">
			<?php echo $this->__('You will be redirected to alipay website when you place an order.') ?>
		</div>
	</ul>
</fieldset>