<?php $_categories = $this->getStoreCategories() ?>
<?php if(count($_categories)): ?>
<div class="nav-container">
  <div id="sidenav">
    <div id="sidenav_header">
       <a id="sidenav-title">All Categories</a>
    </div>
    <div id="custommenu" class="force">
        <?php foreach ($_categories as $_category): ?>
            <?php echo $this->drawCustomMenuItem($_category) ?>
        <?php endforeach ?>
        <div class="clearBoth"></div>
    </div>
  </div>
  <div id="topnav">
      <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('top-cms')->toHtml() ?>
  </div>
</div>
<script type="text/javascript">
//<![CDATA[
var CUSTOMMENU_POPUP_WIDTH = <?php echo (int)Mage::getStoreConfig('custom_menu/popup/width')?>;
var CUSTOMMENU_POPUP_TOP_OFFSET = <?php echo (int)Mage::getStoreConfig('custom_menu/popup/top_offset')?>;
var CUSTOMMENU_POPUP_RIGHT_OFFSET_MIN = <?php echo (int)Mage::getStoreConfig('custom_menu/popup/right_offset_min')?>;
//]]>
</script>

<script type="text/javascript">
jQuery('#sidenav').hover(function() {
      jQuery('#custommenu').addClass('nav-hover');
    }, function() {
      jQuery('#custommenu').removeClass('nav-hover');
    });
</script>

<?php endif ?>
