<div class="block">
    <a style="background-image: url('<?php echo $this->getSkinUrl('images/media/download-webtoprint-extension.jpg') ?>'); width: 195px; height: 85px; display: block;"
       href="http://www.magentocommerce.com/magento-connect/ZetaPrints/extension/1586/web_to_print_store_incl_theme"
       title="Download the latest version" />
  </a>
</div>

<div class="block">
  <div class="block-title">
    <strong><span>W2P resources</span></strong>
  </div>

  <div class="block-content">
    <p class="empty" style="line-height: 1.3em">
      <a href="http://www.zetaprints.com/magento-web-to-print"
         title="Web-to-print and dynamic imaging"
         style="display:block; margin-bottom: 5px">
        Web-to-print software
      </a>

      <a href="http://www.zetaprints.com/help/"
         title="Web-to-print help"
         style="display:block; margin-bottom: 5px">
        Web-to-print help
      </a>

      <a href="http://www.zetaprints.com/magentohelp/"
         title="Magento with web-to-print"
         style="display:block; margin-bottom: 5px">
        Configuration help
      </a>

      <a href="http://www.zetaprints.com/help/category/design-techniques"
         title="Cool web-to-print designs"
         style="display:block; margin-bottom: 5px">
        Design examples
      </a>

      <a href="http://code.google.com/p/magento-w2p/"
         title="Web-to-print and dynamic imaging for magento source code"
         style="display:block; margin-bottom: 5px">
        Source code
      </a>

      <a href="http://www.zetaprints.com/premium/index.php/web-to-print-support.html"
         title="Web-to-print and dynamic imaging support"
         style="display:block;">
        Technical support
      </a>
    </p>
  </div>
</div>
