<ul class="links-2">
	<li class="first"><a href="<?php echo $this->getUrl('catalog/seo_sitemap/product/') ?>"><?php echo $this->__('Product Sitemap') ?></a></li>
	<li><a href="<?php echo $this->getUrl('catalog/seo_sitemap/category/') ?>"><?php echo $this->__('Category Sitemap') ?></a></li>
	<li><a href="<?php echo $this->getUrl('catalogsearch/advanced/') ?>"><?php echo $this->__('Advanced Search') ?></a></li>
	<li><a href="<?php echo $this->getUrl('sales/guest/form/') ?>"><?php echo $this->__('Orders and Returns') ?></a></li>
</ul>