<div class="box base-mini blog">
    <div class="head">
        <h4><?php echo Mage::getStoreConfig('blog/blog/title'); ?></h4>
    </div>
	<div class="content">
<?php if ($posts = $this->getRecent()): ?>
	<h5><?php echo Mage::helper('blog')->__('Recent Posts');?></h5>
    <ul>
	<?php foreach ($posts as $post): ?>
        <li><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle();?></a></li>
    <?php endforeach; ?>
    	<li>&nbsp;</li>
    	</ul>
<?php endif; ?>
   
        <h5><?php echo Mage::helper('blog')->__('Categories');?></h5>
        <ul>
<?php $cats = $this->getCategories(); ?>
<?php foreach ($cats as $cat): ?>
		<li><a href="<?php echo $cat->getAddress(); ?>" ><?php echo $cat->getTitle();?></a></li>
<?php endforeach; ?>
    	</ul>
	</div>
</div>