<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $counter = 1;
?>
<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="left quickview-thumbs">
<?php $_count = $this->getGalleryImages()->count(); ?>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
    	<?php if($counter < 4): ?>
        <p class="clearfix">
            <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(220); ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(80); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
        </p>
        <?php endif;?>
        <?php $counter++;?>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<div class="right">
  <p><img id="quick_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(220) ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel()) ?>" /></p>
  <div class="a-center"><a target="_parent" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel()) ?>" class="link-view">View Product Page &raquo;</a></div>
</div>
<?php else: ?>
<div class="right">
  <p><?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(220).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
  </p>
</div>
<?php endif; ?>