<?php
/**
 * @category    Mana
 * @package     ManaPro_FilterColors
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/**
 * Template for showing options for filter as a list of color boxes
 * @author Mana Team
 * Injected instead of standard catalog/layer/filter.phtml in Mana_Filters_Block_Filter_Attribute init() method.
 */
/* @var $this Mana_Filters_Block_Filter_Attribute */
?>
<ol class="m-filter-colors labels <?php echo $this->getFilterClass() ?>">
    <?php foreach ($this->getItems() as $_item): ?>

    <li <?php if ($_item->getMSelected()): ?>class="m-selected-ln-item"<?php endif; ?>>
    <a href="#"
       onclick="jQuery(this).find('div').<?php echo $_item->getMSelected() ? 'removeClass' : 'addClass' ?>('selected'); setLocation('<?php echo $this->urlEscape($_item->getMSelected() ? $_item->getRemoveUrl() : $_item->getUrl()) ?>'); return false;">
        <div class="m-color <?php if ($_item->getMSelected()): ?>selected<?php endif; ?> <?php echo $this->getFilterValueClass($_item) ?>"
             title="<?php echo $_item->getLabel() ?> (<?php echo $_item->getCount() ?>)">
        </div>
        <?php echo $_item->getLabel() ?>
    </a>
    (<?php echo $_item->getCount() ?>)
    </li>
    <?php endforeach ?>
</ol>
<?php echo Mage::helper('mana_core')->getNamedHtml('mana_filters/markup', 'after_items', array('block' => $this)) ?>
