<?php 
$home = new Mage_Page_Block_Html_Header();
$limit = Mage::getStoreConfig('buyexpress_options/products_block/featured_block');
	  if ($home->getIsHomePage()): ?>   
<?php  

$_products = Mage::getResourceModel('catalog/product_collection')
            ->addAttributeToSelect('name');
   Mage::getModel('catalog/layer')->prepareProductCollection($_products);
            $_products->getSelect()->order('entity_id desc');
$heading = Mage::getStoreConfig('buyexpress_options/products_block');		 
if (count($_products) > 0):
?>
<div class="featured block-product">
	<h2>
		<?php 
			if($heading['featured_block_text']) { 
				echo $heading['featured_block_text']; 
			} else { 
				echo $this->__('Featured Products');
			}
   		?>
    </h2>
  <ul class="products">    
    <?php $i=0; foreach ($_products->getItems() as $_product): if(($_product->featured == 1)): $i++; ?>  
            <li>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(218,150)->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(TRUE) ?>" width="218" height="150" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a>
                <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php if(strlen($this->htmlEscape($_product->getName())) > 35){ 
						echo substr($this->htmlEscape($_product->getName(), 'name'),0,35).'...';
					}else{
						echo $_product->getName();} ?> </a></h3>
                <?php echo $this->getPriceHtml($_product, true, '-new') ?>   
               
					<?php if(($_product->special_price != null)): ?>
                    <div class="promo">
						<?php 
                            $oldPrice = $_product->getPrice();
                            $specialPrice = $_product->getSpecialPrice();
                            $percent = ($oldPrice-$specialPrice)/$oldPrice*100;
                        ?>
                        
                        <p>
                        	<strong><?php echo round($percent); ?><sup>%</sup></strong>
                            <span>OFF</span>
                        </p>
                    </div> 
					<?php endif; ?>  
            </li>
        <?php  
			 
			endif;
			if($limit && $i==$limit){ break; }
			 endforeach; 
		 ?>      
      
</ul> 
<div class="clear"></div>
<?php if($i > 6): ?>
    <ul class="slideBtn">
        <li class="prev"><a href="javascript:void(0);">Prev</a></li>
        <li class="next"><a href="javascript:void(0);">Next</a></li>
    </ul>
<?php endif; ?>
</div>
<?php endif;endif; ?>