<?php $_productCollection=$this->getCollection() ?>
<?php if(!count($_productCollection)){ ?>
<div class="note-msg">
    <?php echo $this->__('There are no products matching the selection.') ?>
</div>
<?php } else { ?>

<?php echo $this->getToolbarHtml() ?>
<?php $_iterator = 0; ?>
<div class="listing-type-list catalog-listing">
<?php foreach ($_productCollection as $_product){ 
	$_iterator++;
?>
    <div style="padding-bottom:40px; padding-top:15px; border-top:1px #CCC solid;">
        <?php // Product data ?>
            <h5><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName())?></a></h5>
            <?php echo $this->getPriceHtml($_product, true) ?>
            <?php if($_product->isSaleable()) { ?>
            <button class="form-button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
            <?php } else { ?>
            <div class="out-of-stock"><?php echo $this->__('Out of stock') ?></div>
            <?php } ?>
    </div>
<?php if($_iterator == 3){ 
		$_iterator=0; ?>
	<div class="clear"></div>
<?php } } ?>
</div>
<?php echo $this->getToolbarHtml() ?>
<?php } ?>
