<?php
/**
 * Magpleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * Magpleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   Magpleasure
 * @package    Magpleasure_Filesystem
 * @version    1.0
 * @copyright  Copyright (c) 2011 Magpleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
?>

<div class="file-tree-wrapper">
    <div class="file-tree" id="file_tree"></div>
</div>

<script type="text/javascript">        
    jQuery(document).ready( function() {
        jQuery('#file_tree').fileTree({
            root: '<?php echo Mage::getBaseDir(); ?>/',
            script: '<?php echo $this->getUrl('filesystem/adminhtml_filesystem/tree', array('isAjax'=> true, 'form_key'=>$this->getFormKey())) ?>',
            expandSpeed: 200,
            collapseSpeed: 200
        }, function(file) {            
            var url = '<?php echo $this->getUrl("filesystem/adminhtml_filesystem/load", array("fn"=>"{{filename}}")) ?>';            
            openFile(url, file);
        });
    });
</script>