<?php
 /*
 * Arcanum Dev AwardPoints
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to arcanumdev@wafunotamago.com so we can send you a copy immediately.
 *
 * @category   Magento Sale Extension
 * @package    AwardPoints
 * @copyright  Copyright (c) 2012 Arcanum Dev. Y.K. (http://arcanumdev.wafunotamago.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="dashboard"><div class="page-title"><h1><?php echo $this->__('My Dashboard') ?></h1></div><?php echo $this->getMessagesBlock()->getGroupedHtml() ?><?php echo $this->getChildHtml('hello') ?><?php echo $this->getChildHtml('top') ?><div class="box-account box-info"><div class="box-head"><h1><?php echo $this->__('Shopping Points') ?></h1></div><?php echo $this->getChildHtml('points') ?></div><div class="box-account box-info"><div class="box-head"><h1><?php echo $this->__('Account Information') ?></h1></div><?php echo $this->getChildHtml('info') ?><?php echo $this->getChildHtml('address') ?></div><?php echo $this->getChildHtml('info1') ?><?php echo $this->getChildHtml('info2') ?></div>