<?php
/**
 * Agence Soon
 *
 * @category    Soon
 * @package     Soon_AdvancedCache
 * @copyright   Copyright (c) 2011 Agence Soon. (http://www.agence-soon.fr)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author      Hervé G. ()
 */
?>
<div id="messages">
    <ul class="messages">
        <li class="notice-msg">
            <ul>
                <li>
                    <?php echo $this->__('Cleaning main "Blocks HTML output" will clean all cache blocks below.'); ?>
                </li>
            </ul>
            
        </li>
    </ul>
</div>