<!-- Slider -->
  <div class="metro-banner-wrapper max-box box-level-3">
    <div id="metro-banner" class="metro-banner">
      <div class="metro-banner-inner">
        <div class="metro-banner-inSide">
        	<a class="metro-banner-slide block-3 bg-color-slider" href="#"> 
            	<span class="imgBox box-level-2 marginNone"> 
                	<img src="{{skin url ='images/slider-1-new.jpg'}}" alt="" /> 
                </span> 
             </a> 
             <a class="metro-banner-slide block-3 bg-color-slider flip" href="#"> 
             	<span class="imgBox box-level-2 marginNone"> 
                	<img src="{{skin url ='images/slider-1-new.jpg'}}" alt="" /> 
                </span> 
             </a> 
             <a class="metro-banner-slide block-3 bg-color-slider" href="#"> 
             	<span class="imgBox box-level-2 marginNone"> 
                	<img src="MetroStyle%20Theme%20Demo_files/slider-8-new.jpg" alt="Beautiful WP Themes" /> 
                </span> 
             </a> 
             <a class="metro-banner-slide block-3 bg-color-slider flip" href="#"> 
             	<span class="imgBox box-level-2 marginNone"> 
                	<img src="{{skin url ='images/slider-1-new.jpg'}}" alt="" /> 
                </span> 
             </a>
         </div>
      </div>
    </div>
  </div>
  <div class="clear anti-mar">&nbsp;</div>
  <div class="metro-banner-control max-box block-h-half bg-color-slider" id="metro-banner-control"> 
  	<a href="#" class="control-left"></a>
      <div class="control-seek">
        <div class="control-seek-box">
          <div class="control-seek-box-inner"></div>
        </div>
      </div>
      <a href="#" class="control-right"></a>
      <div class="clear"></div>
    </div>
  <!-- /Slider -->