<?php 
    $config = Mage::getStoreConfig('mdloption/home_bestseller');
    $categoryId = $config['bestseller'];
	$cObj = Mage::getModel('catalog/category')->load($categoryId);
	
	$visibility = array(
            Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
            Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
        );
	$productObj = $cObj->getProductCollection()->addAttributeToFilter('visibility', $visibility)->getData();
    $_helper = $this->helper('catalog/output');
?>
<?php if($config['bannersetting']):?>
<?php if(count($productObj)<=0): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="headingBox">
<span class="headingIcons featuredIcon"></span>
	<h1 class="line_heading"><?php echo $this->__('Bestseller Products')?></h1>
</div>
<div class="loadBox"><img src="<?php echo $this->getSkinUrl('images/loading.gif'); ?>" /></div>
<div id="mix_container" class="mix_container bestsellerBox" style="display:none;">
<div class="mix_wrapper">
<div class="mix_inner">
    <ul class="bestseller">
      <?php $i=1;foreach($productObj as $_productData): ?>
      <?php $_product = Mage::getModel('catalog/product')->load($_productData['entity_id']); ?>
      <li class="item">
      	<div class="itemInner">
       <div class="badge">			
            <?php if($_product->getData('new')){echo '<span class="new"><b>'. $_product->getAttributeText('new').'</b><strong>'.$this->__('new').'</strong></span>';  }?>
            <?php if($_product->getData('sale')){echo '<span class="sale"><b>'. $_product->getAttributeText('sale').'</b><strong>'.$this->__('sale').'</strong></span>';  }?>
       </div>
       <?php if($config['bestseller_flip_view']==1):?>
          <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
          <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220,215); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
          <img class="hoverImg" src="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(220); ?>" alt="<?php echo $this->htmlEscape($_product['name']); ?>" border="0" />
          </a>
          <?php else: ?>
          <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
          <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220,215); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
          </a>
          <?php endif; ?>
          
          <?php if($config['itemviewbox']==0):?>
              <div class="ic_caption">
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
            
             <?php echo $this->getPriceHtml($_product, true, '-right') ?>      
                    <div class="bottomBox"> 
                    <div class="buttonox">      
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                      </div> 
                     <div class="addBox">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                           <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" rel="tooltip" data-placement="top" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                           <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" rel="tooltip" data-placement="top" class="link-compare"><?php echo $this->__('Add to Compare') ?></a>
                        <?php endif; ?>
                     </div>
                    
                    </div>
               </div>  
          <?php else: ?>
            <div class="ic_caption">
            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
            
             <?php echo $this->getPriceHtml($_product, true, '-right') ?> 
        
                    <div class="bottomBox">
                    
                    <?php if($_product->isSaleable()): ?>
                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                       
                    
                    </div>
               </div>
               <ul class="add-to-links secondBox">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" rel="tooltip" data-placement="top" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                      
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li class="compareR"><a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" rel="tooltip" data-placement="top" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
               </ul>
        <?php endif; ?>
     
          </div>
                  
      </li>
      <?php endforeach ?>
    </ul>
  </div>  
    <div class="clearfix"></div>
    <div class="sliderNab">
        <a id="prev5" class="jcarousel-prev" href="#">&lt;</a>
        <a id="next5" class="jcarousel-next" href="#">&gt;</a>
      </div>
    </div>  
</div>
	<script type="text/javascript">
	jQuery(function(){
		jQuery(window).load(function() {
				jQuery('.loadBox').remove();
				jQuery('.bestsellerBox').slideDown(300);
                    jQuery('.bestseller').carouFredSel({
                        responsive: true,
                        auto:false,
                        prev: '#prev5',
                        next: '#next5',
                        width: '100%',
                        scroll: 2,
                        items: {
                            width:220,
                            visible: {
                                min: 1,
                                max: <?php echo $config['bestsellerItem'];?>
                            }
                        }
                    });
					
        });
	});
    </script>
<?php endif; ?>
<?php endif; ?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.carouFredSel-6.1.0-packed.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.touchSwipe.min.js')?>"></script>