<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/flexslider.css');?>" media="all" />
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.flexslider.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.touchSwipe.min.js'); ?>"></script>
<script type="text/javascript">
jQuery(document).ready(function(){
	 jQuery('.flexsliderSide').flexslider();
	});
</script>
<div class="leftBanner block-banner block">
<div class="slider">
    <div class="flexsliderSide">
     <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block-slide-right')->toHtml() ?>	
    </div>
  </div>
</div>  