 <?php 
    $config = Mage::getStoreConfig('mdloption/newproducts');
    $categoryId = $config['newItemId'];
	$cObj = Mage::getModel('catalog/category')->load($categoryId);
	
	$visibility = array(
            Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
            Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
        );
	$productObj = $cObj->getProductCollection()->addAttributeToFilter('visibility', $visibility)->getData();
    $_helper = $this->helper('catalog/output');
?>
<?php if($config['newProductS']):?>
<?php if(count($productObj)<=0): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="headingBox">
<span class="headingIcons newProductsIcon"></span><h1 class="line_heading"><?php echo $this->__('New Products')?></h1>
<a class="viewAll" href="<?php echo $cObj->getUrl() ?>" title="<?php echo $this->__('View all') ?>" rel="tooltip" data-placement="left">view all</a>
</div>
<div class="category-products">
     <script type="text/javascript">
      		jQuery(document).ready(function(){
				var itemContainerWidth = jQuery('.category-products').width()-12;
				var rowPro = <?php echo $config['rowPro']?>;
				var windowBox = jQuery(window).width();
				var newPro = jQuery('.newProducts .item');
				var resize;
					if(windowBox >1200){
						newPro.width((itemContainerWidth/rowPro)-12);	
					}else{
						newPro.css({width:''});	
					};
					

					jQuery(window).resize(function() {
					  return resize();
					});
					window.onorientationchange = function() {
					  return resize();
					};
					resize = function()	{
						var newPro = jQuery('.newProducts .item');
						var itemContainerWidth = jQuery('.category-products').width()-12;
						var rowPro = <?php echo $config['rowPro']?>;
						var windowBox = jQuery(window).width();	
						if(windowBox >1200){
							newPro.width((itemContainerWidth/rowPro)-12);	
						}else{
							newPro.css({width:''});	
						};
					}
			});
			
      </script>
     <?php
      $eachRowProd = $config['rowPro']; // each row products
	  $productObj = array_slice($productObj,0, $config['newItem']);  
	  $productObj1  = array_chunk($productObj, $eachRowProd);
	 ?>
     <?php foreach($productObj1 as $productObj): ?>
      <ul class="newProducts itemPro item<?php echo $config['rowPro'];?>">
         <?php foreach($productObj as $_productData): ?>
      <?php $_product = Mage::getModel('catalog/product')->load($_productData['entity_id']); ?>
      <li class="item">
      <div class="itemInner">
      <div class="badge">			
            <?php if($_product->getData('new')){echo '<span class="new"><b>'. $_product->getAttributeText('new').'</b><strong>'.$this->__('new').'</strong></span>';  }?>
            <?php if($_product->getData('sale')){echo '<span class="sale"><b>'. $_product->getAttributeText('sale').'</b><strong>'.$this->__('sale').'</strong></span>';  }?>
     </div>
     <?php if($config['flip_view']==1):?>
              <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
              <img class="lazy"  data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(400); ?>" src="<?php echo $this->getSkinUrl('images/loading.gif');?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
              <img class="hoverImg lazy" data-original="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(400); ?>" src="<?php echo $this->getSkinUrl('images/loading.gif');?>" alt="<?php echo $this->htmlEscape($_product['name']); ?>" border="0" />
            </a>
            <?php else:?>
            <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
              <img class="lazy"  data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(400); ?>" src="<?php echo $this->getSkinUrl('images/loading.gif');?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            </a>
        <?php endif;?>
          <?php if($config['itemviewbox']==0):?>
          		<div class="ic_caption">
            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
            
             <?php echo $this->getPriceHtml($_product, true, '-right') ?> 
        
                    <div class="bottomBox">
                    <div class="buttonox">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                      </div> 
                   		<div class="addBox">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                           <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" rel="tooltip" data-placement="top" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                           <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" rel="tooltip" data-placement="top" class="link-compare"><?php echo $this->__('Add to Compare') ?></a>
                        <?php endif; ?>
                        </div>
                   
                    </div>
               </div>
        <?php else: ?>
            <div class="ic_caption">
            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
            
             <?php echo $this->getPriceHtml($_product, true, '-right') ?> 
        
                    <div class="bottomBox">
                    
                    <?php if($_product->isSaleable()): ?>
                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                       
                    
                    </div>
               </div>
        <?php endif; ?>
        <?php if($config['itemviewbox']==0):?>
         	<?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
        <?php else: ?>  
           		<ul class="add-to-links secondBox">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" rel="tooltip" data-placement="top" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                      
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li class="compareR"><a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" rel="tooltip" data-placement="top" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
               </ul>
        <?php endif; ?> 
         </div>      
      </li>
      	<?php endforeach ?>
     </ul>
     <?php endforeach ?>
</div>
<?php endif; ?>
<?php endif; ?>