<?php 
/**
 * Anais_Breadcrumbs extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Anais
 * @package    Anais_Breadcrumbs
 * @copyright  Copyright (c) 2011 Anais Software Services
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */ 
 /**
 * @category   Anais
 * @package    Anais_Breadcrumbs
 * @author     Marius Strajeru <marius.strajeru@anais-it.com>
 */ 
?>
<script type="text/javascript">
//<![CDATA[
    var breadcrumbModel = Class.create();
    breadcrumbModel.prototype = {
	    initialize : function()
	    {
	        this.enabled = $('breadcrumbs_settings_enable_all');
	        if (this.enabled){
	            this.bindEnabledChange();
	            this.refreshEnabledSelect();
	        }
	    },
	    bindEnabledChange: function()
	    {
	        Event.observe(this.enabled, 'change', this.refreshEnabledSelect.bind(this));
	    },
	    refreshEnabledSelect : function()
	    {
	        if (this.enabled.value == 0 || this.enabled.value == '') {
                $('breadcrumbs_settings_enable_specific').up(1).show();
                
	        }
	        else{
                $('breadcrumbs_settings_enable_specific').up(1).hide();
	        }
	    }
	}
	var breadcrumbInstance = new breadcrumbModel();
//]]>
</script>