<html>
<head>
<script type="text/javascript" src="/js/giko/ajaxlogin.js"></script>
</head>
<body>
<div class="col-2">
    <h3><?php echo $this->__('Login') ?></h3>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form id="ajaxlogin_form" action="<?php echo $this->getPostAction() ?>" method="post">
    <fieldset>
        <p><?php echo $this->__('Please log in below:') ?></p>
        <ul class="form-list">
            <li>
                <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
                </div>
            </li>
            <li>
                <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                <div class="input-box">
                    <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                </div>
            </li>
            <li>
            <button type="submit" class="button" onClick="onepageLogin(this)"><span><span><?php echo $this->__('Login') ?></span></span></button>
			NEW CUSTOMERS? 
                <div class="buttons-set">
                    <button type="button" title="<?php echo $this->__('Create an Account') ?>" class="button" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
                </div>
            </li>
        </ul>
    </fieldset>
    </form>
</div>

<script type="text/javascript">
    var loginForm = $('ajaxlogin_form');
    
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
</script>
</body>
</html>