<div class="page-title title-buttons">
    <h1><?php echo $this->__('What happen to your purchase?') ?></h1>
    <a href="#" onclick="window.print(); return false;" class="link-print"><?php echo $this->__('Print This Page') ?></a>
</div>
<div class="whathappen-pop">
	<?php echo $this->getWhatHappen() ?>	
</div>

<div class="buttons-set">
    <button type="button" title="<?php echo $this->__('Close Window') ?>" class="button" onclick="window.close();"><span><span><?php echo $this->__('Close Window') ?></span></span></button>
</div>
<script type="text/javascript">decorateTable('product_comparison');</script>

