<div id="fb-root"></div>
<script src="http://connect.facebook.net/<?php echo Mage::app()->getLocale()->getLocale()?>/all.js#xfbml=1"></script>
<fb:comments
    href="<?php echo Mage::helper('core/url')->getCurrentUrl()?>"
    
  <?php if ($title = Mage::getStoreConfig('amfbreview/general/title')) :?>
    title="<?php echo $this->htmlEscape($title)?>"
    reverse="<?php echo Mage::getStoreConfig('amfbreview/general/ascending') ? 'true' : 'false' ?>"
    numposts="<?php echo Mage::getStoreConfig('amfbreview/general/perpage')?>"
  <?php endif ?>
  
    width="<?php echo Mage::getStoreConfig('amfbreview/display/width')?>"
    simple="<?php echo Mage::getStoreConfig('amfbreview/display/nostyles') ? 'true' : 'false' ?>"
  <?php if ($css = Mage::getStoreConfig('amfbreview/display/css')) :?>
    css="<?php echo Mage::getBaseURL() . $css ?>"
  <?php endif ?>
  
    publish_feed="false"
>
</fb:comments>
<script>
   FB.init({appId  : <?php echo $this->getConfigData('appid') ?>, cookie : true, xfbml  : true, status : true});
</script>