<?php

/**
 * J2T-DESIGN.
 *
 * @category   J2t
 * @package    J2t_Ajaxcheckout
 * @copyright  Copyright (c) 2003-2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    GPL
 */


/*
$this->numberUpsells()
$this->numberUpsellsPerLine()
*/
?>

<div id="back-ajax-add" class="back-ajax-add">
    <a id="j2t-continue-link" class="j2t-continue-link" href="javascript:void(0);" onclick="hideJ2tOverlay();"><span><?php echo $this->__('Continue shopping');?></span></a>
        <span class="j2t-or"><?php echo $this->__('or');?></span>
    <a id="j2t-checkout-link" class="j2t-checkout-link" href="<?php echo $this->getUrl('checkout/cart'); ?>"><span><?php echo $this->__('View cart & checkout');?></span></a>
</div>

<div id="cart_content" class="cart_content"><?php
$count = Mage::helper('checkout/cart')->getSummaryCount();

if( $count == 1 ) {
    echo $this->__('My Cart (%s item)', $count);
} elseif( $count > 0 ) {
    echo $this->__('My Cart (%s items)', $count);
} else {
    echo $this->__('My Cart');
}
?></div>
<div class="cart_side_ajax">
    <?php echo $this->getChildHtml('cart_sidebar_ajax') ?>
</div>
<div class="j2t_ajax_message">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>

<div class="j2t_full_cart_content" id="j2t_full_cart_content">
    <?php echo $this->getChildHtml('cart_content_ajax');?>
</div>