<div id="text_info">
	 
	 <h3 class="in_1em"><a name="#a"></a>Why can you choose Sample Store?</h3>
		<ul>
		<li class="li_width"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/2.png') ?>" /><b>Zero Risk - 100% Satisfaction Guarantee:</b><br /> 
<span>New condition within 7 days of purchase for a full product refund. Product may not be returned in used condition unless defective by manufacturer's warranty.</span></li>
		<li class="li_width"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/4.png') ?>" /><b>Safety and quick shipping to worldwide 
Safety and Quick Shipping To Worldwide:</b> <br />
 <span>The products will be shipped within 24 hours after we received your payment. And we deliver them right to your door in 5-7 working days. You would get high quality shoes from original box. We will ship the new one free in case of being lost during shipping.</span></li>
		<li class="li_width"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/1.png') ?>" /><b>Ordering From www.samplestore.com: </b><br />
<span>After your payment, we assure your item 100% Customs Clearance Guarantee. And we will track your order status everyday in our online order tracking until you get them. If you email us, we will answer you in 24hours online.</span></li>
		<li class="li_width"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/5.png') ?>" /><b>The Lowest Discount Up To 20%-50%:</b> <br />
<span>We, an Internet wholesaler and retailer of original products, have been a Yahoo 5-star merchant and a member of the Better Business Bureau. We send the item from the manufacturer straightly with manufacturer's price to the customers abroad. That's why our products  are cheaper than the market. Please be assured, it's 100% authentic.</span></li>
		<li class="li_width_2"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/3.png') ?>" /><b>Why not become our customer now? </b><br />
<span>Registering to be a member will take only minutes. With your account, you can take part in the various services we offer to you. You will receive free help from our sale representatives, they will answer all of your questions and recommend the latest products to you. Get start buying online now! </span></li>	
 
		</ul>
		<p>  <button type="button" class="button" onclick="window.location='<?php echo $this->getUrl('customer/account/login') ?>';"><span><span><?php echo $this->__('Join Us') ?></span></span></button></p>
		
</div>

