<?php
/**
 * Noovias
 *
 * @category       Noovias
 * @package        Noovias_Cron
 * @copyright      Copyright (c) 2010 <info@noovias.com> - noovias.com
 * @license        http://opensource.org/licenses/osl-3.0.php
 *                 Open Software License (OSL 3.0)
 * @author      noovias.com - Core Team <info@noovias.com>
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;">
                <h3 class="icon-head head-products"><? echo $this->__('Noovias - Cronjobs') ?></h3>
            </td>
        </tr>
    </table>
</div>
<div>
    <? echo $this->getGridHtml(); ?>
</div>
