<img src="<?php echo $this->getSkinUrl('images/needtool_paylogo/logo_alipay.gif') ?>" alt="Alipay" />
<br />
<fieldset class="form-list">
	<?php $_code=$this->getMethodCode() ?>
	<ul id="payment_form_<?php echo $_code ?>" style="display:none">
		<li>
			<?php echo $this->__('You will be redirected to Alipay website when you place an order.') ?>
			<br /><?php echo $this->__('Reference price in RMB are displayed for reference only and exchange rates may different from Alipay.com, the price when you checkout with Alipay should follow the rule from Alipay.com.') ?>
		</li>
	</ul>
</fieldset>