<?php
/**
 * Fontis Recaptcha Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Fontis
 * @package    Fontis_Recaptcha
 * @author     Denis Margetic
 * @author     Chris Norton
 * @copyright  Copyright (c) 2009 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$theme = Mage::getStoreConfig("fontis_recaptcha/setup/theme");
$language = Mage::getStoreConfig("fontis_recaptcha/setup/language");
$publickey = Mage::getStoreConfig("fontis_recaptcha/setup/public_key");
$textbox = Mage::getStoreConfig("fontis_recaptcha/setup/textbox");
?>


<?php if( $theme == 'magento'): ?>

    <?php echo "<script> var RecaptchaOptions = { theme : 'custom', lang : '$language', custom_theme_widget: 'recaptcha_widget' }; </script>"; ?>
    <div id="recaptcha_widget" class="group-select wide fieldset" style="display:none">
        <h2 class="legend" style="background-image: none;">Recaptcha</h2>
        <div style="margin-bottom: 10px; margin-top: 5px;"><?php echo $textbox; ?></div>
        <div class="col2-set">
            <div class="col-1" style="width: 310px; margin-right: 10px; background: transparent; border: 0px none;">
                <div id="recaptcha_image" style="border: 1px solid #CCCCCC; margin-bottom: 10px;"></div>
                <div style="text-align: center;">
                    <span class="recaptcha_only_if_image"><?php echo Mage::getStoreConfig("fontis_recaptcha/magento/text_captcha") ?></span>
                    <span class="recaptcha_only_if_audio"><?php echo Mage::getStoreConfig("fontis_recaptcha/magento/audio_captcha") ?></span>
                    <input type="text" id="recaptcha_response_field" name="recaptcha_response_field" class="input-text required-entry" />
                </div>
            </div>
            <div class="col-2" style="float: left; width: 25px; background: transparent; border: 0px none;">
                <div><a href="javascript:Recaptcha.reload()"><img src="<?php echo $this->getSkinUrl('images/fontis/refresh.png');?>" title="Get another CAPTCHA" alt="Get another CAPTCHA"/></a></div>
                <div class="recaptcha_only_if_image"><a href="javascript:Recaptcha.switch_type('audio')"><img src="<?php echo $this->getSkinUrl('images/fontis/sound.png');?>" title="Get an audio CAPTCHA" alt="Get an audio CAPTCHA"/></a></div>
                <div class="recaptcha_only_if_audio"><a href="javascript:Recaptcha.switch_type('image')"><img src="<?php echo $this->getSkinUrl('images/fontis/text.png');?>" title="Get an image CAPTCHA" alt="Get an image CAPTCHA"/></a></div>
                <div><a href="javascript:Recaptcha.showhelp()"><img src="<?php echo $this->getSkinUrl('images/fontis/help.png');?>" title="Help" alt="Help"/></a></div>
            </div>
        </div>
        <?php echo Mage::helper("fontis_recaptcha")->recaptcha_get_html($publickey, null, Mage::app()->getRequest()->isSecure()); ?>
    </div>

<?php elseif( $theme == 'custom' ): ?>

<p>To create your custom recaptcha theme copy default/templates/fontis/recaptcha.phtml to your_theme/templates/fontis/recaptcha.phtml and replace this text with custom theme code.</p>

<?php else: ?>

    <div style="margin-bottom: 10px;"><?php echo $textbox; ?></div>
    <?php
        echo "<script> var RecaptchaOptions = { theme : '$theme', lang : '$language' }; </script>";
        echo Mage::helper("fontis_recaptcha")->recaptcha_get_html($publickey, null, Mage::app()->getRequest()->isSecure());
    ?>

<?php endif; ?>
