<div class="block-login">
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post">
        <div class="block-content">
            <label for="mini-login"><?php echo $this->__('Email') ?></label>
            <input type="text" name="login[username]" id="mini-login" class="input-text" />
            <label for="mini-password"><?php echo $this->__('Password') ?></label>
            <input type="password" name="login[password]" id="mini-password" class="input-text" />
            <div class="actions">
                <button type="submit" class="button"><span><span><?php echo $this->__('Login') ?></span></span></button>
            </div>
        </div>
    </form>
</div>

<div class="new-customer">
	<p><?php echo $this->__('Don’t have an account yet?') ?></p>
    <?php 
		$helper = Mage::helper("customer"); 
		$regUrl = $helper->getRegisterUrl();
		$logUrl = $helper->getLoginUrl();					  
	?>
    <a href="<?php echo $regUrl; ?>"><?php echo $this->__('Register Free!'); ?></a>
</div>
