
<?php if ($this->getMethod()->getMailingAddress() || $this->getMethod()->getPayableTo()): ?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <div class="input-box">
            <?php if ($this->getMethod()->getPayableTo()): ?>
                <?php echo $this->__('<label>Make Check payable to</label>: %s', $this->getMethod()->getPayableTo()) ?><br />
            <?php endif; ?>
            <?php if ($this->getMethod()->getMailingAddress()): ?>
                <label><?php echo Mage::helper('payment')->__('Send Check to:') ?></label>
                <div class="checkmo-mailing-address">
                    <?php echo nl2br($this->getMethod()->getMailingAddress()) ?>
                </div>
            <?php endif; ?>
        </div>
    </li>
</ul>
<?php endif; ?>
