
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
        <li>
            <div class="input-box">
                <label for="po_number"><?php echo $this->__('Purchase Order Number') ?> <span class="required">*</span></label><br />
                <input type="text" id="po_number" name="payment[po_number]" title="<?php echo $this->__("Purchase Order Number") ?>" class="required-entry input-text" value="<?php echo $this->htmlEscape($this->getInfoData('po_number')) ?>"/>
            </div>
        </li>
    </ul>
</fieldset>