<div id="back-ajax-add" class="back-ajax-add">

<button id="mdl-continue-link" onclick="hideMdlOverlay();" class="button btn-mdlcart" title="<?php echo $this->__('Continue shopping');?>" type="button"><span><span><?php echo $this->__('Continue shopping');?></span></span></button>
<button onclick="location.href='<?php echo $this->getUrl('checkout/cart'); ?>'" id="mdl-checkout-link" class="button mdlcheckout" title="<?php echo $this->__('View cart & checkout');?>" type="button"><span><span><?php echo $this->__('View cart & checkout');?></span></span></button>
</div>

<div id="cart_content" class="cart_content"><?php
$count = Mage::helper('checkout/cart')->getSummaryCount();

if( $count == 1 ) {
    echo $this->__('My Cart (%s item)', $count);
} elseif( $count > 0 ) {
    echo $this->__('My Cart (%s items)', $count);
} else {
    echo $this->__('My Cart');
}
?></div>
<div class="cart_side_ajax">
    <?php echo $this->getChildHtml('cart_sidebar_ajax') ?>
</div>
<div class="mdl_ajax_message">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>

<div class="mdl_full_cart_content" id="mdl_full_cart_content">
    <?php echo $this->getChildHtml('cart_content_ajax');?>
</div>