<?php
	
/*
 * Magento EsayCheckout Extension
 *
 * @copyright:	EcommerceTeam (http://www.ecommerce-team.com)
 * @version:	1.0
 *
 */
	
?><div class="easy-step" id="easycheckout-review">
	<h2><?php echo $this->__('Order Review');?></h2>
	<div class="info" id="easycheckout-review-info">
		<?php echo $this->getChildHtml('info');?>
	</div>
	<div class="agreements">
		<?php echo $this->getChildHtml('agreements') ?>
	</div>
</div>