
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>

<?php
if(Mage::helper("ExtraConfig")->is_mobile() == true) {
    $layout = 'vertical';
} else {
    $layout = Mage::helper("ExtraConfig")->themeOptions('productlayout');
    $lyt = $_product->getAttributeText('productlayout');
    if($lyt != null){ $layout = $lyt; }
}
if ($layout == 'default')
{ ?>


<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 1) {
   
    
    $gallery .= '<div id="slider" class="flexslider">';
    $gallery .= '<h2>' . $this->__('More Views') . '</h2>';
    $gallery .= '<ul class="slides">';
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->constrainOnly(true)->keepAspectRatio(true)->resize(69,69) . '" width="69" height="69" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                 .  '</a></li>';
    }
    $gallery .= '</ul></div>';
} else {
				
$gallery .= '<div class="without-image"></div>';

}
?>

<?php
}
elseif ($layout == 'horizontal')
{ ?>


<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 1) {
    
    $gallery .= '<div id="slider" class="flexslider">';
    $gallery .= '<h2>' . $this->__('More Views') . '</h2>';
    $gallery .= '<ul class="slides">';
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->constrainOnly(true)->keepAspectRatio(true)->resize(69,69) . '" width="69" height="69" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                 .  '</a></li>';
    }
    $gallery .= '</ul></div>';
} else {
				
 $gallery .= '<div class="without-image"></div>';

}
?>

<?php
}
elseif ($layout == 'vertical')
{ ?>


<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 1) {
    
    $gallery .= '<div id="slider" class="flexslider">';
    $gallery .= '<h2>' . $this->__('More Views') . '</h2>';
    $gallery .= '<ul class="slides">';
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->constrainOnly(true)->keepAspectRatio(true)->resize(69,69) . '" width="69" height="69" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                 .  '</a></li>';
    }
    $gallery .= '</ul></div>';
} else {
				
$gallery .= '<div class="without-image"></div>';

}
?>


<?php
}
elseif ($layout == 'custom1')
{ ?>


<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 1) {
    
    $gallery .= '<div id="slider" class="flexslider">';
    $gallery .= '<h2>' . $this->__('More Views') . '</h2>';
    $gallery .= '<ul class="slides">';
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->constrainOnly(true)->keepAspectRatio(true)->resize(69,69) . '" width="69" height="69" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                 .  '</a></li>';
    }
    $gallery .= '</ul></div>';
} else {
				
$gallery .= '<div class="without-image"></div>';

}
?>

<?php
}
elseif ($layout == 'custom2')
{ ?>

<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 1) {
    
    $gallery .= '<div id="carousel2" class="flexslider"><ul class="slides">';
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->constrainOnly(true)->keepAspectRatio(true)->resize(69,69) . '" width="69" height="69" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                 .  '</a></li>';
    }
    $gallery .= '</ul></div>';
} else {
				
$gallery .= '<div class="without-image"></div>';

}
?>

<?php } ?>



<?php
if ($layout == 'default')
{ ?>

    <?php if(isset($gallery)): ?>
       
	
        <div class="default-views detail-carousel cloudzoom">
				<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
				<p class="product-image product-image-zoom">
				    <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
				    <?php
					$_img = '<img id="image" src="'.$this->getCloudImage($_product)->constrainOnly(true)->keepAspectRatio(true).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				    </a>
				</p>
				<?php endif; ?>
        

				 <?php echo $gallery; ?>
        
        
        
        </div>
    <?php endif; ?>
 <script>
  j$('#slider').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 75,
    itemMargin: 10
  });
   
 
   
  
</script>
 <?php
}
elseif ($layout == 'horizontal')
{ ?>   
    
    <?php if(isset($gallery)): ?>
       
	
        <div class="horizontal-views detail-carousel cloudzoom">
         
				<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
				<p class="product-image product-image-zoom">
				    <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
				    <?php
					$_img = '<img id="image" src="'.$this->getCloudImage($_product)->constrainOnly(true)->keepAspectRatio(true).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				    </a>
				</p>
				<?php endif; ?>

				 <?php echo $gallery; ?>
        
        
        
        </div>
    <?php endif; ?>
 <script>
  j$('#slider').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 75,
    itemMargin: 10
  });
   
 
   
  
</script>
    
    <?php
}
elseif ($layout == 'vertical')
{ ?>
    
    <?php if(isset($gallery)): ?>
       
	
        <div class="vertical-views detail-carousel cloudzoom">
         
				<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
				<p class="product-image product-image-zoom">
				    <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
				    <?php
					$_img = '<img id="image" src="'.$this->getCloudImage($_product)->constrainOnly(true)->keepAspectRatio(true).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				    </a>
				</p>
				<?php endif; ?>

				<?php echo $gallery; ?>
        
        
        
        </div>
    <?php endif; ?>
 <script>
  j$('#slider').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 75,
    itemMargin: 10
  });
   
  
   
  
</script>
    
    
    <?php
}
elseif ($layout == 'custom1')
{ ?>   
    
    <?php if(isset($gallery)): ?>
       
	
        <div class="custom1-views detail-carousel cloudzoom">
         
				<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
				<p class="product-image product-image-zoom">
				    <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
				    <?php
					$_img = '<img id="image" src="'.$this->getCloudImage($_product)->constrainOnly(true)->keepAspectRatio(true).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				    </a>
				</p>
				<?php endif; ?>

				<?php echo $gallery; ?>
        
        
        
        </div>
    <?php endif; ?>
 <script>
 j$('#slider').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 75,
    itemMargin: 10
  });
   
  
   
  
</script>
    
    
    <?php
}
elseif ($layout == 'custom2')
{ ?>

<?php if(isset($gallery)): ?>
       
	
        <div class="custom2-views detail-carousel cloudzoom">
				
				
				
				<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
				<p class="product-image product-image-zoom">
				    <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
				    <?php
					$_img = '<img id="image" src="'.$this->getCloudImage($_product)->constrainOnly(true)->keepAspectRatio(true).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				    </a>
				</p>
				<?php endif; ?>

				<?php echo $gallery; ?>
        
        
        
        </div>
    <?php endif; ?>
 <script>
  j$('#carousel2').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    direction: "vertical",
    slideshow: false,
    //itemWidth: 75,
    itemMargin: 10
  });
   
 
  
</script>

<?php
}
?>
    



