<?php
/**
 * Magpleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * Magpleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   Magpleasure
 * @package    Magpleasure_Common
 * @version    0.6.11
 * @copyright  Copyright (c) 2012-2013 Magpleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
?>
<?php /** @var $this Magpleasure_Common_Block_Adminhtml_Widget_Treeview_Root */ ?>
<div class="magpleasure-treeview-root">
    <div id="magpleasure_treeview_tree" class="magpleasure-treeview-tree categories-side-col">
        <?php echo $this->getTreeHtml(); ?>
    </div>
    <div id="magpleasure_treeview_form" class="magpleasure-treeview-form">
        <?php echo $this->getContainerHtml(); ?>
    </div>
    <div class="fixed"></div>
</div>
<script type="text/javascript">
//<![CDATA[

var <?php echo $this->getJsObjectName(); ?> = new MpAdminhtmlWidgetTreeviewRoot({

});

//]]>
</script>

