


<div class='entry-edit'>
    <div class="entry-edit-head"><h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Setting'); ?> </h4></div>
    <div class="fieldset" id='cron-setting'>
        <table>
            <thead> 
                <tr><th><?php $this->__('Days of the week');?></th><th width='20'></th><th colspan='4'><?php $this->__('Hours of the day');?></th></tr>
            </thead>
            <tr>
                <td width='300'>
                    <div class='cron-d-box'><input class='cron-box' value='Monday' id="d-Monday" type='checkbox'/> <?php echo $this->__('Monday'); ?></div>
                    <div class='cron-d-box'><input class='cron-box' value='Tuesday' id="d-Tuesday" type='checkbox'/> <?php echo $this->__('Tuesday'); ?></div>
                    <div class='cron-d-box'><input class='cron-box' value='Wednesday' id="d-Wednesday" type='checkbox'/> <?php echo $this->__('Wednesday'); ?></div>
                    <div class='cron-d-box'><input class='cron-box' value='Thursday' id="d-Thursday" type='checkbox'/> <?php echo $this->__('Thursday'); ?></div>
                    <div class='cron-d-box'><input class='cron-box' value='Friday' id="d-Friday" type='checkbox'/> <?php echo $this->__('Friday'); ?></div>
                    <div class='cron-d-box'><input class='cron-box' value='Saturday' id="d-Saturday" type='checkbox'/> <?php echo $this->__('Saturday'); ?></div>
                    <div class='cron-d-box'><input class='cron-box' value='Sunday' id="d-Sunday" type='checkbox'/> <?php echo $this->__('Sunday'); ?></div>
                </td>
                <td></td>
                <td width='150' class='morning-half'>
                    <div class='cron-h-box'><input class='cron-box' value='00:00' id='h-0000'  type='checkbox'/> <?php echo $this->__('00:00 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='01:00' id='h-0100' type='checkbox'/> <?php echo $this->__('01:00 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='02:00' id='h-0200' type='checkbox'/> <?php echo $this->__('02:00 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='03:00' id='h-0300' type='checkbox'/> <?php echo $this->__('03:00 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='04:00' id='h-0400' type='checkbox'/> <?php echo $this->__('04:00 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='05:00' id='h-0500' type='checkbox'/> <?php echo $this->__('05:00 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='06:00' id='h-0600'  type='checkbox'/> <?php echo $this->__('06:00 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='07:00' id='h-0700' type='checkbox'/> <?php echo $this->__('07:00 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='08:00' id='h-0800'  type='checkbox'/> <?php echo $this->__('08:00 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='09:00' id='h-0900' type='checkbox'/> <?php echo $this->__('09:00 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='10:00' id='h-1000' type='checkbox'/> <?php echo $this->__('10:00 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='11:00' id='h-1100' type='checkbox'/> <?php echo $this->__('11:00 AM'); ?></div>

                </td>
                <td width='150' class='morning'>
                    <div class='cron-h-box'><input class='cron-box' value='00:30' id='h-0030' type='checkbox'/> <?php echo $this->__('00:30 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='01:30' id='h-0130' type='checkbox'/> <?php echo $this->__('01:30 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='02:30' id='h-0230' type='checkbox'/> <?php echo $this->__('02:30 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='03:30' id='h-0330' type='checkbox'/> <?php echo $this->__('03:30 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='04:30' id='h-0430' type='checkbox'/> <?php echo $this->__('04:30 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='05:30' id='h-0530' type='checkbox'/> <?php echo $this->__('05:30 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='06:30' id='h-0630' type='checkbox'/> <?php echo $this->__('06:30 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='07:30' id='h-0730' type='checkbox'/> <?php echo $this->__('07:30 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='08:30' id='h-0830' type='checkbox'/> <?php echo $this->__('08:30 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='09:30' id='h-0930' type='checkbox'/> <?php echo $this->__('09:30 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='10:30' id='h-1030' type='checkbox'/> <?php echo $this->__('10:30 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='11:30' id='h-1130' type='checkbox'/> <?php echo $this->__('11:30 AM'); ?></div>




                </td>
                <td width='150' class='afternoon-half'>
                    <div class='cron-h-box'><input class='cron-box' value='12:00' id='h-1200' type='checkbox'/> <?php echo $this->__('12:00 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='13:00' id='h-1300' type='checkbox'/> <?php echo $this->__('01:00 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='14:00' id='h-1400' type='checkbox'/> <?php echo $this->__('02:00 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='15:00' id='h-1500' type='checkbox'/> <?php echo $this->__('03:00 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='16:00' id='h-1600' type='checkbox'/> <?php echo $this->__('04:00 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='17:00' id='h-1700' type='checkbox'/> <?php echo $this->__('05:00 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='18:00' id='h-1800' type='checkbox'/> <?php echo $this->__('06:00 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='19:00' id='h-1900' type='checkbox'/> <?php echo $this->__('07:00 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='20:00' id='h-2000' type='checkbox'/> <?php echo $this->__('08:00 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='21:00' id='h-2100' type='checkbox'/> <?php echo $this->__('09:00 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='22:00' id='h-2200' type='checkbox'/> <?php echo $this->__('10:00 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='23:00' id='h-2300' type='checkbox'/> <?php echo $this->__('11:00 PM'); ?></div>

                </td>
                <td width='150' class='afternoon'>
                    <div class='cron-h-box'><input class='cron-box' value='12:30' id='h-1230' type='checkbox'/> <?php echo $this->__('12:30 AM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='13:30' id='h-1330' type='checkbox'/> <?php echo $this->__('01:30 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='14:30' id='h-1430' type='checkbox'/> <?php echo $this->__('02:30 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='15:30' id='h-1530' type='checkbox'/> <?php echo $this->__('03:30 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='16:30' id='h-1630' type='checkbox'/> <?php echo $this->__('04:30 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='17:30' id='h-1730' type='checkbox'/> <?php echo $this->__('05:30 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='18:30' id='h-1830' type='checkbox'/> <?php echo $this->__('06:30 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='19:30' id='h-1930' type='checkbox'/> <?php echo $this->__('07:30 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='20:30' id='h-2030' type='checkbox'/> <?php echo $this->__('08:30 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='21:30' id='h-2130' type='checkbox'/> <?php echo $this->__('09:30 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='22:30' id='h-2230' type='checkbox'/> <?php echo $this->__('10:30 PM'); ?></div>
                    <div class='cron-h-box'><input class='cron-box' value='23:30' id='h-2330' type='checkbox'/> <?php echo $this->__('11:30 PM'); ?></div>


                </td>
            </tr>
        </table>



    </div>


