<?php
/*                                                                       *
* This script is part of the epoq Recommendation Service project         *
*                                                                        *
* TypoGento is free software; you can redistribute it and/or modify it   *
* under the terms of the GNU General Public License version 2 as         *
* published by the Free Software Foundation.                             *
*                                                                        *
* This script is distributed in the hope that it will be useful, but     *
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHAN-    *
* TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General      *
* Public License for more details.                                       *
*                                                                        *
* @version $Id: product.phtml 487 2010-08-05 12:32:57Z weller $
* @license http://opensource.org/licenses/gpl-license.php GNU Public License, version 2
*/
?>

<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="collateral-box up-sell">
    <div class="head"><h4><?php echo $this->__('epoq: You may also be interested in the following product(s)') ?></h4></div>
    <table cellspacing="0" class="generic-product-grid catalog-listing" id="epoq-product-table">
    <?php // $this->setColumnCount(4); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <tr>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
            <td>
                <p class="product-image"><a href="<?php echo $_link->getProductUrl() ?>" class="epoq-recommentation-link"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(125) ?>" width="125" height="125" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a></p>
                <h5><a href="<?php echo $_link->getProductUrl() ?>"  class="epoq-recommentation-link"><?php echo $this->htmlEscape($_link->getName()) ?></a></h5>
                <?php echo $this->getPriceHtml($_link, true) ?>
                <?php echo $this->getReviewsSummaryHtml($_link) ?>
            </td>
            <?php else: ?>
            <td class="empty-product">&nbsp;</td>
            <?php endif; ?>
        <?php endfor; ?>
        </tr>
    <?php endfor; ?>
    </table>
    <script type="text/javascript">decorateTable('upsell-product-table')</script>
</div>
<script type="text/javascript">
$$('a.epoq-recommentation-link').each(function(elem, index){
	var newParam = 'recommentation_id=<?php echo $this->getSession()->getLastRecommentationId();?>',
	params = '?' + newParam;
    params = elem.href.replace(new RegExp('[\?&]' + 'recommentation_id' + '[^&]*'), '$1' + newParam);
    if (params === elem.href) {
        if(elem.href.indexOf('?') == '-1'){
    		params += '?' + newParam;
        }else{
        	params += '&' + newParam;
        }
    }
    elem.href = params;
});
</script>
<?php endif ?>
