<?php

/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Productquestions
 * @copyright  Copyright (c) 2008-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */

$questions = $this->_collection;

?>
<div class="productquestions-container">

<h2><?php echo $this->__('Questions on %s', $this->getProduct()->getName()) ?></h2>

<?php if($questions->getSize()): ?>
    <?php echo $this->getChildHtml('productquestions_sorter'); ?>
    <?php if($this->getShowPager()) echo $this->getChildHtml('productquestions_pager'); ?>

    <ul>
    <?php foreach($questions->getItems() as $q): ?>
        <a name="<?php echo $q->getId() ?>"> </a>
        <li class="record"><?php echo $this->__('From') ?> <b><?php echo $q->getQuestionAuthorName() ?></b> at <span class="date"><?php echo $this->formatDate($q->getQuestionDate()) ?> <?php echo $this->formatTime($q->getQuestionDate()) ?></span>
            <ul >
                <li class="question"><?php echo nl2br(htmlentities($q->getQuestionText(), null, 'UTF-8')) ?></li>
                <li class="reply"><em><?php echo AW_Productquestions_Helper_Data::parseURLsIntoLinks($q->getQuestionReplyText()) ?></em></li>
    <?php if($this->getVotingAllowed()): ?>
                    <li class="helpfulness"><?php echo $this->__('Do you find this question helpful?'); ?>&nbsp;
                        <strong>
                            <a style="color: green; cursor:pointer;" onclick="setLocation('<?php echo $this->getUrl('productquestions/index/vote', array('id' => $q->getId(), 'value' => 1)) ?>')"><?php echo $this->__('Yes') ?></a>
                        </strong>
                        &nbsp;
                        <strong>
                            <a style="color: red; cursor:pointer;" onclick="setLocation('<?php echo $this->getUrl('productquestions/index/vote', array('id' => $q->getId(), 'value' => 0)) ?>')"><?php echo $this->__('No') ?></a>
                        </strong>
                    </li>
    <?php endif; ?>
            </ul>
        </li>
    <?php endforeach; ?> 
    </ul>
<?php else: ?>
    <p><?php echo $this->__('No questions asked yet'); ?></p>
<?php endif; ?>

<?php echo $this->getChildHtml('productquestions_form'); ?>

</div>