<?php if ($this->canShow()): ?>
	<?php $characterCount = $this->getCharacterCount(); ?>
	<div id='deliverynote'>
		<label for='deliverynote-note'><?php echo $this->__(Mage::helper('deliverynote')->getFrontendLabel()) ?><?php if ($characterCount !== false): ?> ( max <?php echo $characterCount ?> characters ) <?php endif; ?></label>
		<textarea id='deliverynote-note' name='deliverynote-note' class="input-text<?php if ($characterCount !== false): ?> validate-length maximum-length-<?php echo $characterCount ?> <?php endif; ?>"></textarea>
	</div>
<?php endif; ?>