<?php if (($_products = $this->getProductCollection()) && $_collectionSize = $_products->getSize()): ?>
<div class="box-recent-review" >
    <div class="head"><span><?php echo $this->__($this->getTitle()) ?></span></div>
    <div id="reviewed_box" class="reviewed_box">
    <ul class="items-content" >
    <?php  foreach ($_products->getItems() as $_product): ?>
         <li class="item-list">
            
            <span class="reviewimg">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                    <img class="product-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(45) ?>" width="45" height="45" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                </a>
            </span>
            <span class="reviewname"><a class="product-name" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></span>
            <span class="reviewtitle"><a href="<?php echo $_product->getProductUrl() ?>#customer-reviews" ><?php echo $this->htmlEscape($_product->getTitle()) ?></a></span> 
	    
	    <span class="reviewauthor"><span>By</span><?php echo $this->__(' %s', $this->htmlEscape($_product->getNickname())) ?></span>
        </li>
    <?php endforeach; ?>
    </ul>
    </div>
    <script type="text/javascript">decorateGeneric($$('.item-list'), ['last', 'odd', 'even']);</script>
</div>
<?php endif; ?>