<?php 
    $_productCollection=$this->getLoadedProductCollection();
?>
<?php if($_productCollection->count()): ?>
  <div>
    <ul>
      <?php $_collectionSize = $_productCollection->count() ?>
      <?php $_columnCount = $this->getColumnCount(); ?>
      <?php $i=0; foreach ($_productCollection as $_product): ?>
      <li> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a><a class="quickview" href="<?php echo Mage::getBaseUrl(); ?>catalog/ajax_product/view/id/<?php echo $_product->getId(); ?>">Quickview</a>
        <?php 
                  $current_date = date("Y-m-d",strtotime(Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT))); 
                  $from_date = date("Y-m-d",strtotime($_product->getResource()->getAttribute('news_from_date')->getFrontend()->getValue($_product)));
                  $to_date = date("Y-m-d",strtotime($_product->getResource()->getAttribute('news_to_date')->getFrontend()->getValue($_product))); 
                  if ($current_date >= $from_date && $current_date <= $to_date):?>
        <img src="<?php echo $this->getSkinUrl('images/label-new.png')?>" alt="new" class="new"/>
        <?php endif;?>
      </li>
      <?php endforeach ?>
    </ul>
  </div>
<?php endif;?>