<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>
<?php

/*$customer_id = Mage::getSingleton('customer/session')->getCustomerId(); 
$store_id = Mage::app()->getStore()->getId();

//echo "$customer_id $store_id";
Mage::getModel('rewardpoints/observer')->processRecordFlat($customer_id, $store_id);*/
/*$order = Mage::getModel('sales/order')->loadByIncrementId('300000004');
$quote = Mage::getModel('sales/quote')->load($order->getQuoteId());
$rewardPoints = Mage::helper('rewardpoints/data')->getPointsOnOrder($order, null, 1);
echo $rewardPoints;*/

?>
<table class="data-table" id="my-rewardpoints-table">
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
            <tr>
                <th><?php echo $this->__('Your Points') ?></th>
                <th><?php echo $this->__('Total Accumulated Points') ?></th>
                <th><?php echo $this->__('Total Points Spent') ?></th>
                <th><?php echo $this->__('Points waiting for validation') ?></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><?php echo $this->getPointsCurrent(); ?></td>
                <td>
                    <?php echo $this->getPointsReceived(); ?>
                    <?php if ($points_lost = $this->getPointsLost()):?>
                    <div class="j2t-point-lost"><?php echo $this->__("You also have %s expired points.", $points_lost);?></div>
                    <?php endif;?>
                </td>
                <td><?php echo $this->getPointsSpent(); ?></td>
                <td><?php echo $this->getPointsWaitingValidation(); ?></td>
            </tr>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-rewardpoints-table')</script>