<?php 
/**
 * @category    Mana
 * @package     ManaPro_FilterCheckboxes
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/** 
 * Template for showing options for filter as a HTML list 
 * @author Mana Team
 * Injected instead of standard catalog/layer/filter.phtml in Mana_Filters_Block_Filter_Attribute constructor.
 * This template is overridden by copying (template body was pasted from catalog/layer/filter.phtml 
 * and modified as needed). All changes are marked with comments.
 */
/* @var $this Mana_Filters_Block_Filter_Attribute */
?>
<ol class="m-filter-css-checkboxes">
<?php foreach ($this->getItems() as $_item): ?>
    <li <?php if ($_item->getMSelected()): ?>class="m-selected-ln-item"<?php endif; ?>>
        <?php // MANA BEGIN ?>
	        <a class="<?php echo $_item->getMSelected() ? 'm-checkbox-checked' : 'm-checkbox-unchecked' ?>" 
	        onclick="this.className='<?php echo $_item->getMSelected() ? 'm-checkbox-unchecked' : 'm-checkbox-checked' ?>'; setLocation('<?php echo $this->urlEscape($_item->getMSelected() ? $_item->getRemoveUrl() : $_item->getUrl()) ?>'); return false;"
            href="#" title="<?php echo $_item->getLabel() ?>"><?php echo $_item->getLabel() ?></a>
        <?php // MANA END ?>
        (<?php echo $_item->getCount() ?>)
    </li>
<?php endforeach ?>
</ol>
<?php echo Mage::helper('mana_core')->getNamedHtml('mana_filters/markup', 'after_items', array('block' => $this)) ?>
