<?php
/**
 * Magpleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * Magpleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   Magpleasure
 * @package    Magpleasure_Common
 * @version    0.6.11
 * @copyright  Copyright (c) 2012-2013 Magpleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
?>
<?php /** @var $this Magpleasure_Common_Block_Adminhtml_Widget_Treeview_Tree */ ?>
<?php if ($headerText = $this->getHeaderText()): ?>
<div class="content-header">
    <h3 class="icon-head head-categories"><?php echo $this->escapeHtml($headerText); ?></h3>
</div>
<?php endif; ?>
<?php echo $this->getAdditionalHeaderContent(); ?>
<?php echo $this->getStoreSwitcherHtml();?>

<div class="tree-holder">
    <div id="<?php echo $this->getHtmlId(); ?>" style="width:100%; overflow:auto;">




    </div>
</div>

<script type="text/javascript">
//<![CDATA[

Ext.onReady(function(){
    // shorthand
    var Tree = Ext.tree;

    var tree = new Tree.TreePanel('<?php echo $this->getHtmlId(); ?>', {
        animate:true,
        loader: new Tree.TreeLoader({
            dataUrl:'<?php echo $this->getDataUrl(); ?>'
        }),
        enableDD:true,
        containerScroll: true
    });

    // set the root node
    var root = new Tree.AsyncTreeNode({
        text: '<?php echo $this->__("Extended Menu"); ?>',
        draggable:false,
        id:'0'
    });

    tree.setRootNode(root);

    // render the tree
    tree.render();
    root.expand();
});



//]]>
</script>

