<div class="entry-edit">
  <div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">Display settings</h4>
  </div>
  <div class="fieldset fieldset-wide">
    <div class="hor-scroll">
      <table cellspacing="0" class="form-list">
        <tbody>
          <tr>
            <td class="label"><label for="">Name</label></td>
            <td class="value">

            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
