<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>
<div class="page-head">
    <h3><?php echo $this->__('Referral') ?></h3>
</div>
<?php if($this->getReferrerPoints()):?>
    <?php echo $this->__('For any first valid order placed by referred friend, you earn: <strong>%s points</strong>', $this->getReferrerPoints());?>
    <br />
<?php endif;?>
<?php if($this->getFriendPoints()):?>
    <?php echo $this->__('For any first valid order placed by referred friend, your friend gets: <strong>%s extra points</strong>', $this->getFriendPoints());?>
<?php endif;?>

<?php if($this->isAddthis() || $this->isPermanentLink()):?>
<div class="account-box ad-account-info box">
    <?php if($this->isPermanentLink()):?>
    <div class="box-account box-recent">
        <div class="head box-title">
            <h3><?php echo $this->__('Permanent Link') ?></h3>
        </div>
        <?php echo $this->__('Share the following link with your friends: <br /><strong>%s</strong>', $this->getReferringUrl()) ?>
    </div>
    <?php endif;?>


    <?php if($this->isAddthis()):?>
    <div class="box-account box-recent">
        <fieldset class="group-select">
            
            <div class="head box-title">
                <h3><?php echo $this->__('Share referring link') ?></h3>
            </div>
            <ul>
                <li>
                    <div class="input-box">
                        <label for="j2t-share-title"><?php echo $this->__('Sharing title (may not be used)') ?></label><br />
                        <input onkeyup="j2tReinitializeAddThis();" type="text" name="j2t-share-title" id="j2t-share-title" value="<?php echo $this->__('Great deals here!');?>" class="input-text" />
                    </div>
                    <div class="input-box">
                        <label for="j2t-share-text"><?php echo $this->__('Sharing text (may not be used)') ?></label><br />
                        <textarea onkeyup="j2tReinitializeAddThis();" id="j2t-share-text" name="j2t-share-text" cols="100" rows="5" class="input-text"><?php echo $this->__('Visit this for great deals!');?></textarea>
                    </div>
                </li>
            </ul>
        </fieldset>
    
        <br />
        <a class="addthis_button" id="j2t-post-share" addthis:url="<?php echo $this->getReferringUrl();?>" addthis:title="<?php echo $this->__('Great deals here!');?>" addthis:description="<?php echo $this->__('Visit this for great deals!');?>"></a>
        <script type="text/javascript">
            function j2tReinitializeAddThis(){
              if (window.addthis){
                 $('j2t-post-share').writeAttribute('addthis:title', $('j2t-share-title').value);
                 $('j2t-post-share').writeAttribute('addthis:description', $('j2t-share-text').value);
                 window.addthis.ost = 0;
                 window.addthis.ready();
              }
           }
            //addthis.button('#j2t-post-share', {}, {url: "<?php echo $this->getReferringUrl();?>", title: $('j2t-share-title').value, description: $('j2t-share-text').value});
            addthis.button('#j2t-post-share');
        </script>
    </div>
    <?php endif;?>
</div>
<?php endif;?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('rewardpoints/index/referral/') ?>" method="post" id="form-validate">
    <div class="box-account box-recent">
        <fieldset class="group-select">
            <input type="hidden" value="Il1NwrpfsCuSmp03" name="form_key"/>
            <div class="head box-title">
                <h3><?php echo $this->__('Refer a friend') ?></h3>
            </div>
            <ul>
                <li>
                    <div class="input-box">
                        <label for="name"><?php echo $this->__('Friend\'s name') ?> <span class="required">*</span></label><br />
                        <input type="text" name="name" value="" title="<?php echo $this->__('Friend\' name') ?>" class="required-entry input-text" id="name" />
                    </div>
                    <div class="input-box">
                        <label for="email"><?php echo $this->__('Friend\'s email address') ?> <span class="required">*</span></label><br />
                        <input type="text" name="email" id="email" title="<?php echo $this->__('Friend\'s email address') ?>" value="" class="required-entry input-text" />
                    </div>
                </li>
            </ul>
        </fieldset>
        <div class="button-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <!--<a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back') ?></a>-->
            <button class="form-button button" type="submit"><span><span><?php echo $this->__('Send') ?></span></span></button>
        </div>
    </div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate', true);
</script>
<br /><br />
<?php $_referred = $this->getReferred();?>
<?php if($_referred->getSize()): ?>
<?php echo $this->getPagerHtml() ?>
<table cellspacing="0" class="data-table" id="referred-friends-table">
    <thead>
        <tr>
            <?php ?><th><?php echo $this->__('Full Name') ?></th><?php ?>
            <th><?php echo $this->__('Email') ?></th>
            <!--<th><?php echo $this->__('Registered?') ?></th>-->
            <th><?php echo $this->__('First order?') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_referred as $_friend): ?>
            <tr>
                <?php ?><td><?php echo $_friend->getRewardpoints_referral_name() ?></td><?php ?>
                <td><?php echo $_friend->getRewardpoints_referral_email() ?></td>
                <!--<td><?php echo $_friend->getRewardpoints_referral_child_id() ? $this->__('yes') : $this->__('no') ?></td>-->
                <td class="a-right"><?php echo $_friend->getRewardpoints_referral_status() ? $this->__('yes') : $this->__('no') ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->getPagerHtml() ?>
<?php else: ?>
    <p><?php echo $this->__('You haven\'t invited any friend.'); ?></p>
<?php endif ?>