<h3>UPGRADE </h3>
<p>
Due to the lack of activity in this highly demanded extension development, aheadWorks has 
agreed with the owner and previous developer lazzymonk on moving the ownership rights to 
our company. We are already well known in modules development sphere and decided to take 
our chance to make a valuable contribution to the community. So we must answer the first 
question that could arise immediately - yes, the extension continues to be free and open 
source despite it changes its license and owner. We'll try to dedicate more efforts to 
the development to make this extension better and better and satisfy growing needs of 
the community. 
</p> 
<h3>NEW EXTENSION PAGE </h3>
Please note that this is the last release of the extension on lazzymonk's page - since 
we are significantly changing and improving the whole extension engine we decided to 
create a new extension page. Generally, this release is dedicated for store owners who 
do not check the extension page - the package contains notification to download the 
new version from the new extension page. So please visit <a href="http://www.magentocommerce.com/extension/1516">http://www.magentocommerce.com/extension/1516</a> and get the new release 
from there.
