<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Apptha_Smoovpay
 * @copyright  Copyright (c) 2011 ContusSupport 
 */
?>
<fieldset class="form-list">
    <?php $_code = $this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo Mage::helper('smoovpay')->__('You will be redirected to Smoovpay website when you place an order.') ?><br/>
            <img src="https://www.smoovpay.com/img/btn_smoovpay_v1.png"  alt="SmoovPay!" />

        </li>
    </ul>
</fieldset>