<?php
/**
 * KH_CartQtyButtons cartqtybuttons.xml
 * 
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category design
 * @package default_default
 * @author KevinHorst IT <info@kevinhorst.de>
 * @copyright Copyright (c) 2011 <info@kevinhorst.de> - KevinHorst IT
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software 
 */
?>

<?php
/**
 * JS block for including settings/render
 *
 * @see Mage_Core_Block_Template
 */

$_data = array(
	'increase qty' => $this->__('increase qty'),
	'decrease qty' => $this->__('decrease qty'),);
?>
<script type="text/javascript">
Translator.add(<?php echo Zend_Json::encode($_data) ?>);

//<![CDATA[
if (!window.KH) {
	var KH = {};
}

if (!window.KH.CartQtyButtons) {
	KH.CartQtyButtons = {};
}

KH.CartQtyButtons.Settings = {};
KH.CartQtyButtons.Settings.selector = "<?php echo $this->helper('CartQtyButtons')->getJsSelector() ?>";
KH.CartQtyButtons.Settings.position = "<?php echo $this->helper('CartQtyButtons')->getBtnPosition() ?>";
KH.CartQtyButtons.Settings.nullBehavior = <?php echo $this->helper('CartQtyButtons')->getNullBehavior() ?>;
KH.CartQtyButtons.Settings.items = <?php echo Zend_Json::encode($this->helper('CartQtyButtons')->getStepInformation()) ?>;

var cartQtyButtonsRender = new KH.CartQtyButtons.Render(KH.CartQtyButtons.Settings, Translator);
//]]>
</script>
