<?php

/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Productquestions
 * @copyright  Copyright (c) 2008-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */

$allowedSortings = AW_Productquestions_Block_Sorter::getAllowedSorting();
if(count($allowedSortings)):
    list($sortOrder, $sortDir) = $this->getCurrentSorting();
    $invertedDir = AW_Productquestions_Block_Sorter::getInvertedDir($sortDir);
?>

<div class="pager">
    <div class="limiter">
        <?php echo $this->__('Sort by') ?>
        <select onchange="setLocation(this.value)" style="width:120px;">
        <?php foreach($allowedSortings as $sortKey => $sortName): ?>
            <option value="<?php echo $this->getSortOrderUrl($sortKey) ?>" <?php if($sortKey == $sortOrder): ?> selected="selected"<?php endif ?>> <?php echo $sortName ?></option>
        <?php endforeach ?>
        </select>
        <a href="<?php echo $this->getSortDirUrl($invertedDir) ?>"><img src="<?php echo $this->getSkinUrl('images/aw_productquestions/sort_'.strtolower($sortDir).'_arrow.gif') ?>" alt="<?php echo AW_Productquestions_Model_Source_Question_Sorting::getSortDirDescription($invertedDir) ?>" /></a>
    </div>
</div>

<?php endif; ?>
